using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Eventbus.Generator;

[Generator(LanguageNames.CSharp)]
public class SourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(static m => m is not null);

        var collectedHandlers = handlerDeclarations.Collect();

        context.RegisterSourceOutput(collectedHandlers,
            static (spc, handlers) => Execute(spc, handlers));
    }

    private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext ctx)
    {
        var classSymbol = ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol;

        return classSymbol != null && classSymbol.AllInterfaces.Any(i => i.Name == "IRecipient")
            ? classSymbol
            : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> handlers)
    {
        CreateEventbus(context, handlers);
        CreateExtensionMethod(context, handlers);
    }

    private static void CreateExtensionMethod(SourceProductionContext context,
        ImmutableArray<INamedTypeSymbol?> handlers)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Eventbus.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class EventbusExtensions");
        sb.AppendLine("{");
        sb.AppendLine("     extension(IServiceCollection services)");
        sb.AppendLine("     {");
        sb.AppendLine("         public void AddSingletonEventbusServices()");
        sb.AppendLine("         {");
        sb.AppendLine("             services.AddSingleton<global::Eventbus.Contract.IEventPublisher, EventBus>();");
        if (!handlers.IsDefaultOrEmpty)
        {
            foreach (var recipients in handlers)
            {
                if (recipients == null) continue;

                var recipientInterfaces = recipients.AllInterfaces.Where(i =>
                    i.Name == "IRecipient" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Eventbus.Contract"));

                foreach (var interfaceSymbol in recipientInterfaces)
                {
                    if (interfaceSymbol.TypeArguments.Length != 1) continue;

                    var eventType = interfaceSymbol.TypeArguments[0]
                        .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var recipientType = recipients.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    sb.AppendLine(
                        $"             services.AddSingleton<global::Eventbus.Contract.IRecipient<{eventType}>, {recipientType}>();");
                }
            }
        }

        sb.AppendLine("         }");
        sb.AppendLine("     }");
        sb.AppendLine("}");

        context.AddSource("EventbusExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void CreateEventbus(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> recipients)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Eventbus.Contract;");
        sb.AppendLine();
        sb.AppendLine("namespace Eventbus.Generated;");
        sb.AppendLine();
        sb.AppendLine("public class EventBus : global::Eventbus.Contract.IEventPublisher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly Dictionary<Type, List<Func<object, Task>>> _handlers = new();");
        sb.AppendLine();
        sb.AppendLine("    public EventBus(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        if (!recipients.IsDefaultOrEmpty)
        {
            foreach (var handler in recipients)
            {
                if (handler == null) continue;

                var recipientInterfaces = handler.AllInterfaces.Where(i =>
                    i.Name == "IRecipient" &&
                    i.ContainingNamespace.ToDisplayString().Contains("Eventbus.Contract"));

                foreach (var interfaceSymbol in recipientInterfaces)
                {
                    if (interfaceSymbol.TypeArguments.Length != 1) continue;

                    var eventType = interfaceSymbol.TypeArguments[0]
                        .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var recipientType = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    sb.AppendLine(
                        $"        AddInternal(serviceProvider.GetService(typeof({recipientType})) as IRecipient<{eventType}>);");
                }
            }
            sb.AppendLine("    }");
        }
        sb.AppendLine();
        sb.AppendLine("  private void AddInternal<TEvent>(IRecipient<TEvent>? recipient)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (recipient == null) return;");
        sb.AppendLine();
        sb.AppendLine("        var type = typeof(TEvent);");
        sb.AppendLine("        if (!_handlers.TryGetValue(type, out var list))");
        sb.AppendLine("        {");
        sb.AppendLine("            list = new List<Func<object, Task>>();");
        sb.AppendLine("            _handlers.Add(type, list);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        _handlers[type].Add(e => recipient.Receive((TEvent)e));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async Task Publish<TEvent>(TEvent @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (@event == null) return;");
        sb.AppendLine();
        sb.AppendLine("        if (_handlers.TryGetValue(typeof(TEvent), out var handlers))");
        sb.AppendLine("        {");
        sb.AppendLine("            var tasks = handlers.Select(handle => handle(@event));");
        sb.AppendLine("            await Task.WhenAll(tasks);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        context.AddSource("SourceEventbus.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}